### ISSUE TITLE
Damage will not be applied PF1e 10.3

### ISSUE THREAD

**Issue by skyly87** [Nevela-0/PF1-Automate-Damage#9]
- German:
Wenn versucht wird Schaden anzuwenden, werden bei Charaktere die kein Schadensreduzierung oder Energie Resistenzen haben, keine Schaden verrechnet.

- English:
When attempting to apply damage, no damage is dealt to characters that do not have damage reduction or energy resistance.

![image](https://github.com/Nevela-0/PF1-Automate-Damage/assets/1340423/2f235262-37be-4ffe-8825-208e83e70251)

**Comment by mageofthesands** [comment]
I can confirm.  I don't get an error in the console though.  Just... nothing.

**Comment by Nevela-0** [comment]
I can't reproduce the issue.
Please give more information (what is the damage source? weapon, spell etc)
You can contact me on discord if you'd like.

**Comment by Nevela-0** [comment]
With the help of @mageofthesands, I found that the bug is less about Automate Damage and more about a bad migration (usually because of worlds with many actors \ tokens).

Tokens and Actors created on PF1Ev9.x do not have data like weapon materials, addons, ammo, etc and Automate Damage attempts to access those properties. It fails so it crashes.

The reason it fails is that during the migration process sometimes some of the items of an actor will not migrate fully and properties like weapon material for example will not be added and when Automate Damage tries to access it, it will fail. Even if I make it not crash it will still not receive that property and just move on to calculate things without considering material or addons.

v0.9.5 should handle errors better.
